apiVersion: v1
kind: Pod
metadata:
  name: alpaca-prod
  labels:
    ver: 1.0.0
    app: alpaca
    env: prod
spec:
  replicas: 3
  containers:
  - name: kuard
    image: blaxers/kuardrep
    
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
