apiVersion: v1
kind: Pod
metadata:
  name: alpaca-prod
  labels:
    ver: 1,
    app: alpaca,
    env: prod
spec:
  replicas: 2
  containers:
  - image: blaxers/kuard:blue
    name: alpaca-prod
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
