apiVersion: v1
kind: Pod
metadata:
  name: alpaca-test
  labels:
    ver: 2.0.0
    app: alpaca
    env: test
spec:
  replicas: 1
  containers:
  - name: kuard
    image: blaxers/kuardrep
    
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
