apiVersion: v1
kind: Pod
metadata:
  name: bandicoot-prod
  labels:
    ver: 2.0.0
    app: bandicoot
    env: prod
spec:
  replicas: 2
  containers:
  - name: kuard
    image: blaxers/kuardrep
    
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
